### ISSUE TITLE
MaxSize is only checked in client side

### ISSUE THREAD

**Issue by socketubs** [jyap808/g0bin#1]
MaxSize is only checked in client side here: https://github.com/jyap808/g0bin/blob/master/static/js/behavior.js#L534-L544

It means that anybody can upload file using API that will bypass this check. Something like that:

```shell
curl 'https://paste.example.com/paste/create'\
    -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8'\
    -H 'Accept: */*'\
    --data 'content=%7B%22iv%22%3A%224YZSIXrG%2BLny7vvD8FFVfw%22%2C%22salt%22%3A%22jAX9Tv6QTnc%22%2C%22ct%22%3A%22VH5dGGnhbwHn45rT8GSfmg%22%7fdD&expiration=burn_after_reading'
```

I think we could check content size before saving `Paste` here: https://github.com/jyap808/g0bin/blob/master/g0bin.go#L232-L241

**Comment by jyap808** [comment]
Nice work. Closed #4
